version: '3'
services:
  backend:
    build: ./api-vacinas
    ports:
      - "3000:3000"
    networks:
      - vacinas-net

  frontend:
    build: ./VaxiAgenda
    ports:
      - "8100:80"
    depends_on:
      - backend
    networks:
      - vacinas-net

networks:
  vacinas-net:
